@startuml

package rpg {

package ingredients {

class IngredientType {
+ standardTemperature: long[2]
+ simpleName: String
}

class AlchemicIngredient {
+ completeName: String
+ specialName: String
+ ingredientType: IngredientType
+ state: State
+ {static} amount: int
+ {static} quantity: Quantity
+ coldness: int
+ hotness: int

+ getSimpleName(): String
+ getCompleteName(): String
+ getSpecialName(): String
+ getTemperature(): long[2]
}

class IngredientContainer {
+ ingredient: AlchemicIngredient
+ quantity: Quantity
+ capacity: int
}

class Quantity {
}

enum QuantityLiquid {
+ drop: int
+ spoon: int
+ vial: int
+ bottle: int
+ jug: int
+ barrel: int
+ storeroom: int
}

enum State {
+ LIQUID
+ POWDER
}

enum QuantityPowder {
+ pinch: int
+ spoon: int
+ sachet: int
+ box: int
+ sack: int
+ chest: int
+ storeroom: int
}

IngredientContainer <-- AlchemicIngredient
AlchemicIngredient --> "1" IngredientType
AlchemicIngredient -- "1" Quantity
Quantity -- QuantityLiquid
Quantity -- QuantityPowder
Quantity -- IngredientContainer
State - AlchemicIngredient : use

note left of Quantity: Dit is nog wat vaag. \nIk weet niet hoe \nwe dit het best doen.
}

package lab {

abstract Device {
+ labo: Laboratory

+ input(IngredientContainer container): void
+ getBack(IngredientContainer container): IngredientContainer
+ execute(): IngredientContainer
}

class CoolingBox extends Device {
+ ingredient: AlchemicIngredient
+ temperature: int
}

class Oven extends Device {
+ ingredient: AlchemicIngredient
+ temperature: int
}

class Kettle extends Device {
+ ingredients: ArrayList<IngredientContainer>
}

class Transmogrifier extends Device {
+ ingredient: AlchemicIngredient
}

class Laboratory {
+ capacity: int
+ ingredients: ArrayList<IngredientContainer>
+ coolingBox: coolingBox
+ oven: Oven
+ kettle: Ketlle
+ transmogrifier: Transmogrifier

+ input()
+ getBack()
+ addDevice()
+ removeDevice()
+ execute(Recipe, int)
}

CoolingBox "1" -- "1" Laboratory
Oven "1" -- "1" Laboratory
Kettle "1" -- "1" Laboratory
Transmogrifier "1" -- "1" Laboratory

}

IngredientContainer -- Laboratory

package recipe {

enum Operations {
+ ADD
+ HEAT
+ COOL
+ MIX
}

class Recipe {
+ instructions: ArrayList<Operations>
+ ingredients: ArrayList<AlchemicIngredient>
}

class RecipeBook {
+ recipes: ArrayList<Recipe>

+ Recipebook()
+ addRecipe(Recipe recipe): void
+ removeRecipe(Recipe recipe): void
}

RecipeBook <-- "0..*" Recipe
Recipe - Operations
Recipe <-- AlchemicIngredient

}
}

@enduml